import type { BookingRequest } from './types'

export const trustedBooking: BookingRequest = {
  booking_id: 'BKG-1001',
  agent_id: 'AGT-TRUSTED',
  account_age_days: 1200,
  total_bookings_90d: 500,
  chargebacks_90d: 0,
  cancellations_90d: 12,
  bookings_24h: 4,
  recent_holds_24h: 2,
  recent_late_cancellations_90d: 0,
  seats_requested: 2,
  hours_until_departure: 240,
  ip_country: 'IN',
  card_country: 'IN',
  payment_attempts_10m: 1,
  device_linked_to_fraud: false,
  card_on_blocklist: false,
  interaction_duration_seconds: 94,
  fields_pasted: 1,
  pointer_events: 46,
}

export const paymentRiskBooking: BookingRequest = {
  ...trustedBooking,
  booking_id: 'BKG-2048',
  agent_id: 'AGT-2048',
  account_age_days: 2,
  total_bookings_90d: 12,
  chargebacks_90d: 2,
  cancellations_90d: 1,
  bookings_24h: 18,
  hours_until_departure: 1.4,
  ip_country: 'RU',
  card_country: 'IN',
  payment_attempts_10m: 7,
  device_linked_to_fraud: true,
  interaction_duration_seconds: 5,
  fields_pasted: 8,
  pointer_events: 1,
}

export const inventoryRiskBooking: BookingRequest = {
  ...trustedBooking,
  booking_id: 'BKG-7310',
  agent_id: 'AGT-7310',
  account_age_days: 180,
  total_bookings_90d: 90,
  cancellations_90d: 48,
  bookings_24h: 42,
  recent_holds_24h: 24,
  recent_late_cancellations_90d: 8,
  seats_requested: 32,
  hours_until_departure: 72,
  interaction_duration_seconds: 61,
  fields_pasted: 2,
  pointer_events: 31,
}